services:
  ob:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Better auth need these values at *build* time
        BETTER_AUTH_URL: http://0.0.0.0:3000
        BETTER_AUTH_SECRET: xxxxxSuperSecretKeyxxxxx

        # Static env vars need for svelte to resolve at build time
        NOTE_DIR: ./data
        DB_PATH: file:./data/.data.db
    ports:
      - "3000:3000"
    volumes:
      # Store the db and the secret
      - ./data:/app/data
      # Store the notes
      - ./notes:/app/notes
    environment:
        # Origin must match the URL you use to access the app
      - ORIGIN=http://0.0.0.0:3000
      - BASE_URL=http://0.0.0.0:3000/
      - VITE_BETTER_AUTH_URL=http://0.0.0.0:3000