services:
  ob:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./db:/app/db
    environment:
      - ORIGIN=http://localhost:3000
      - BETTER_AUTH_URL=http://localhost:3000
      - VITE_BETTER_AUTH_URL=http://localhost:3000
      - BASE_URL=http://localhost:3000/